ALTER TABLE "User"
  ADD COLUMN "avatarUrl" TEXT,
  ADD COLUMN "bio" TEXT,
  ADD COLUMN "birthYear" INTEGER,
  ADD COLUMN "gender" TEXT,
  ADD COLUMN "heightCm" DOUBLE PRECISION,
  ADD COLUMN "weightKg" DOUBLE PRECISION,
  ADD COLUMN "themeMode" TEXT NOT NULL DEFAULT 'system',
  ADD COLUMN "locale" TEXT NOT NULL DEFAULT 'zh-CN';
